(import scheme (chicken base) (chicken port) (chicken condition) (chicken string) (chicken sort)
        (aux unittest) (aux base) (aux fds unionfind))

;; Ported from on-scheme's tests/unionfind-test.scm: the 16 original
;; assertions are all here; each `(test #t (and (member? ...) ...))` block is
;; split into one ⊨ per edge, so that a failure names the wrong edge.

(define-suite unionfind-suite

  ((test-find-and-union _)
   (unionfind-new
     (λ (U ↑ ↑! ≡ →)
       (⊦= 'absent (↑ 'absent))
       (⊦= '(a b) (↑ '(a b))) ; this example doesn't work in Python because lists are *not* hashable objects
       (⊦= 0 (length (→)))
       (≡ 3 4)
       (⊦= 4 (↑ 3))
       (⊦= 4 (↑ 4))
       (let1 (edges (→))
         (⊦= '(3 . 4) (assoc 3 edges))
         (⊦= '(4 . 4) (assoc 4 edges)))
       ;; the original printer test was commented out because it depends on
       ;; hash iteration order: check only that each line is present.
       (let1 (s (with-output-to-string (λ () (display U))))
         (⊨ (and (substring-index "(4 -> 4)\n" s) #t))
         (⊨ (and (substring-index "(3 -> 4)\n" s) #t))
         (⊦= (string-length "(4 -> 4)\n(3 -> 4)\n") (string-length s))))))

  ((test-union-by-rank _)
   (unionfind-new
     (λ (U ↑ ↑! ≡ →)
       (⊦= 0 (length (→)))
       (≡ 'A 'D)
       (≡ 'B 'E)
       (≡ 'C 'F)
       (let1 (edges (unionfind->→+★ U))
         (⊨ (member? '((A . 0) (D . 1)) edges))
         (⊨ (member? '((B . 0) (E . 1)) edges))
         (⊨ (member? '((C . 0) (F . 1)) edges))
         (⊨ (member? '((D . 1) (D . 1)) edges))
         (⊨ (member? '((E . 1) (E . 1)) edges))
         (⊨ (member? '((F . 1) (F . 1)) edges)))
       (≡ 'C 'G)
       (≡ 'E 'A)
       (let1 (edges (unionfind->→+★ U))
         (⊨ (member? '((A . 0) (D . 2)) edges))
         (⊨ (member? '((E . 1) (D . 2)) edges))
         (⊨ (member? '((B . 0) (E . 1)) edges))
         (⊨ (member? '((C . 0) (F . 1)) edges))
         (⊨ (member? '((G . 0) (F . 1)) edges))
         (⊨ (member? '((D . 2) (D . 2)) edges))
         (⊨ (member? '((F . 1) (F . 1)) edges)))
       (≡ 'B 'G)
       (let1 (edges (unionfind->→+★ U))
         (⊨ (member? '((A . 0) (D . 2)) edges))
         (⊨ (member? '((E . 1) (D . 2)) edges))
         (⊨ (member? '((B . 0) (E . 1)) edges))
         (⊨ (member? '((C . 0) (F . 1)) edges))
         (⊨ (member? '((G . 0) (F . 1)) edges))
         (⊨ (member? '((D . 2) (D . 2)) edges))
         (⊨ (member? '((F . 1) (D . 2)) edges))))))

  ((test-path-compression _)
   (unionfind-new
     (λ (U ↑ ↑! ≡ →)
       (≡ 'B 'A)
       (≡ 'D 'C)
       (≡ 'C 'A)
       (≡ 'I 'F)
       (≡ 'J 'F)
       (≡ 'K 'G)
       (≡ 'H 'E)
       (≡ 'F 'E)
       (≡ 'G 'E)
       (≡ 'E 'A)

       (let1 (edges (unionfind->→+★ U))
         (⊨ (member? '((B . 0) (A . 3)) edges))
         (⊨ (member? '((C . 1) (A . 3)) edges))
         (⊨ (member? '((D . 0) (C . 1)) edges))
         (⊨ (member? '((E . 2) (A . 3)) edges))
         (⊨ (member? '((F . 1) (E . 2)) edges))
         (⊨ (member? '((G . 1) (E . 2)) edges))
         (⊨ (member? '((I . 0) (F . 1)) edges))
         (⊨ (member? '((J . 0) (F . 1)) edges))
         (⊨ (member? '((K . 0) (G . 1)) edges))
         (⊨ (member? '((H . 0) (E . 2)) edges)))

       (⊦= 'A (↑! 'I))

       (let1 (edges (unionfind->→+★ U))
         (⊨ (member? '((B . 0) (A . 3)) edges))
         (⊨ (member? '((C . 1) (A . 3)) edges))
         (⊨ (member? '((D . 0) (C . 1)) edges))
         (⊨ (member? '((E . 2) (A . 3)) edges))
         (⊨ (member? '((F . 1) (A . 3)) edges))
         (⊨ (member? '((G . 1) (E . 2)) edges))
         (⊨ (member? '((I . 0) (A . 3)) edges))
         (⊨ (member? '((J . 0) (F . 1)) edges))
         (⊨ (member? '((K . 0) (G . 1)) edges))
         (⊨ (member? '((H . 0) (E . 2)) edges)))

       (⊦= 'A (↑! 'K))

       (let1 (edges (unionfind->→+★ U))
         (⊨ (member? '((B . 0) (A . 3)) edges))
         (⊨ (member? '((C . 1) (A . 3)) edges))
         (⊨ (member? '((D . 0) (C . 1)) edges))
         (⊨ (member? '((E . 2) (A . 3)) edges))
         (⊨ (member? '((F . 1) (A . 3)) edges))
         (⊨ (member? '((G . 1) (A . 3)) edges))
         (⊨ (member? '((I . 0) (A . 3)) edges))
         (⊨ (member? '((J . 0) (F . 1)) edges))
         (⊨ (member? '((K . 0) (A . 3)) edges))
         (⊨ (member? '((H . 0) (E . 2)) edges))))))

  ;; New cases, for the API the original tests did not exercise.

  ((test-edges-size-copy _)
   (let* ((U (unionfind-empty))
          (≡ (unionfind-≡ U)))
     (⊨ (unionfind? U))
     (⊦= 0 (unionfind-size U))
     (⊦= 0 (unionfind-edges U))
     (≡ 1 2)
     (≡ 3 4)
     (⊦= 4 (unionfind-size U))
     (⊦= 2 (unionfind-edges U))
     (⊦= '(1 2 3 4) (sort (unionfind-keys U) <))
     (let* ((W (unionfind-copy U))
            (≡W (unionfind-≡ W)))
       (≡W 2 4)
       (≡W 5 6)
       (⊦= 6 (unionfind-size W))
       (⊦= 4 (unionfind-edges W))
       (⊦= ((unionfind-↑ W) 1) ((unionfind-↑ W) 3))
       ;; the original is untouched by the unions on the copy
       (⊦= 4 (unionfind-size U))
       (⊦= 2 (unionfind-edges U))
       (⊦= 2 ((unionfind-↑ U) 1))
       (⊦= 4 ((unionfind-↑ U) 3))
       (⊦= 1 ((unionfind-★ U) 2)))))

  ((test-walk-and-accessors _)
   (let1 (U (unionfind-empty))
     (unionfind-accessors U
       (λ (↑ ↑! ≡ →)
         (≡ 'x 'y)
         (≡ 'y 'z)
         (⊦= (↑ 'x) (↑ 'z))
         (⊦= 3 (length (→)))))
     (⊦= 3 (unionfind-walk U (λ (k v) (void)) (λ () (unionfind-size U))))
     (let1 (links '())
       (unionfind-walk/without-loops U
         (λ (k v) (set! links (cons k links)))
         (λ () (⊦= 2 (length links))))
       (⊭ (member? ((unionfind-↑ U) 'x) links)))))

  ((test-rank-absent _)
   ;; strict error check (design §0.6): ⊦⧳ does not fail when nothing is raised.
   (let1 (U (unionfind-empty))
     (⊨ (condition-case (begin ((unionfind-★ U) 'nope) #f) ((exn) #t)))
     (⊦= 'nope ((unionfind-↑ U) 'nope))
     (⊦= 'nope ((unionfind-↑! U) 'nope))
     (⊦= '() (unionfind->→+★ U)))))

(unittest/✓ unionfind-suite)
